### ISSUE TITLE
Include statements at root level break other include statements

### ISSUE THREAD

**Issue by AdrianCert** [AdunSG/yaml-extender#1]
Include statements at root level break other include statements

For demonstrating that you can see:
> As note, please comment first line and check the diferences

```yaml
xyml.include: prop.yaml
pipelines:
  node:
    name: "sss"
    stages:
      - xyml.include: file-a.yaml
      - xyml.include: file-b.yaml<<order=23>>

```

```yaml
# prop.yaml
VAR_NAME: My name is
VAR_BR_NAME: master
```

```yaml
# file-a.yaml
name: "VENV"
order: 12
steps:
  - cmd: ..\venv.bat create pipfile
  - cmd: ..\venv.bat python --version
  ```
  
  ```yaml
  # file-b.yaml
name: "ASTREE"
order: "{{xyml.param.order}}"
steps:
  - cmd: bla bla
    name: Some work
```
