### ISSUE TITLE
Include parameters break inline for loop

### ISSUE THREAD

**Issue by FlTr** [AdunSG/yaml-extender#10]
As soon as there is a include parameter, the inline for loop is broken. A simple for loop still works as expected.

Considering the two yaml files *foo* and *bar*.

**First scenario:** *foo* includes *bar* without parameter:
```yaml
# foo.yaml
array:
  - version: 1.2
  - version: 4.2

nodes:
  xyml.include:
    - bar.yaml
```

```yaml
# bar.yaml
- name: bar
  param: "{{param}}"
  steps:
    - xyml.for: i:array
      version: "{{i.version}}"
    - all_versions: "{{xyml.for:i:array:{{i.version}} }}"
```
Results in:
```yaml
array:
- version: 1.2
- version: 4.2
nodes:
- name: bar
  param: '{{param}}'
  steps:
  - version: 1.2
  - version: 4.2
  - all_versions: '1.2 4.2 '
```

**Second scenario:** *foo* includes *bar* with parameter:
```yaml
# foo.yaml
array:
  - version: 1.2
  - version: 4.2

nodes:
  xyml.include:
    - bar.yaml<<param=42>>
```
Results in:
```yaml
array:
- version: 1.2
- version: 4.2
nodes:
- name: bar
  param: 42
  steps:
  - version: 1.2
  - version: 4.2
  - all_versions: i:array:{{i.version}}
```
