### ISSUE TITLE
Extending lists with xyml.for 

### ISSUE THREAD

**Issue by Ch3ri0ur** [AdunSG/yaml-extender#2]
Hi, some early users tried to extend a list with a for loop. they tried:

```yaml
parallelBuild:
- name: test1
  buildTarget: BUILD
- name: test2
  buildTarget: BUILD

pipelines:
- nodes:
  - label: Should stay
    executionOrder: 0
    stages:
      - name: "Should stay stage"
        executionOrder: 0

  xyml.for: build_config:parallelBuild
  xyml.content:
  - label: "{{build_config.name}}"
    executionOrder: 1
    stages:
      - name: "{{build_config.buildTarget}}"
        executionOrder: 0
```
This swallows the node and results in:
```yaml
parallelBuild:
- name: test1
  buildTarget: BUILD
- name: test2
  buildTarget: BUILD
pipelines:
- label: test1
  executionOrder: 1
  stages:
  - name: BUILD
    executionOrder: 0
- label: test2
  executionOrder: 1
  stages:
  - name: BUILD
    executionOrder: 0

```

If we indent the xyml.for etc. into a list it works as expected.

```yaml
parallelBuild:
- name: test1
  buildTarget: BUILD
- name: test2
  buildTarget: BUILD

pipelines:
- nodes:
  - label: Should stay
    executionOrder: 0
    stages:
      - name: "Should stay stage"
        executionOrder: 0

  - xyml.for: build_config:parallelBuild
    xyml.content:
    - label: "{{build_config.name}}"
      executionOrder: 1
      stages:
        - name: "{{build_config.buildTarget}}"
          executionOrder: 0
```

Creates the expected 
```yaml
parallelBuild:
- name: test1
  buildTarget: BUILD
- name: test2
  buildTarget: BUILD
pipelines:
- nodes:
  - label: Should stay
    executionOrder: 0
    stages:
    - name: Should stay stage
      executionOrder: 0
  - label: test1
    executionOrder: 1
    stages:
    - name: BUILD
      executionOrder: 0
  - label: test2
    executionOrder: 1
    stages:
    - name: BUILD
      executionOrder: 0
```

Is this the expected behavior?
Should we maybe extend the documentation on how to extend lists?

**Comment by AdrianCert** [comment]
I think so, it is somehow an expected behavior for how this package works!
The first time it tries to load the yaml content and the `xyml.for` is direct child for `pipelines[0]` (first item of list) so this will join into an object with `nodes`, `xyml.for`, `xyml.content` and this will couse the ignoring what you have as a key near those keywords.

At `src\yaml_extender\resolver\inline_loop_resolver.py:28` `k = pipelines` and `self._Resolver__resolve returns <<what you have in results>>`

**Comment by AdunSG** [comment]
Hi,
The xyml.for statement needs to be a member of the node. Not of the Pipeline.
Just add an additional indentation, No need to make IT a list though.

**Comment by Ch3ri0ur** [comment]
> Hi, The xyml.for statement needs to be a member of the node. Not of the Pipeline. Just add an additional indentation, No need to make IT a list though.

If I understood you correctly, is this what you mean? That swallows everything else in that node. So we do need to move it to its own list entry.

```yaml
parallelBuild:
- name: test1
  buildTarget: BUILD
- name: test2
  buildTarget: BUILD

pipelines:
- nodes:
  - label: Should stay
    executionOrder: 0
    stages:
      - name: "Should stay stage"
        executionOrder: 0

    xyml.for: build_config:parallelBuild
    xyml.content:
    - label: "{{build_config.name}}"
      executionOrder: 1
      stages:
        - name: "{{build_config.buildTarget}}"
          executionOrder: 0
```


```yaml
parallelBuild:
- name: test1
  buildTarget: BUILD
- name: test2
  buildTarget: BUILD
pipelines:
- nodes:
  - label: test1
    executionOrder: 1
    stages:
    - name: BUILD
      executionOrder: 0
  - label: test2
    executionOrder: 1
    stages:
    - name: BUILD
      executionOrder: 0
```

Other example

```yaml
parallelBuild:
- name: test1
  buildTarget: BUILD
- name: test2
  buildTarget: BUILD

pipelines:
- nodes:
  - label: XXXXX
    executionOrder: 0
    stages:
      - name: "XXXXX"
        executionOrder: 0

  - label: Should stay
    executionOrder: 0
    stages:
      - name: "Should stay stage"
        executionOrder: 0

    xyml.for: build_config:parallelBuild
    xyml.content:
    - label: "{{build_config.name}}"
      executionOrder: 1
      stages:
        - name: "{{build_config.buildTarget}}"
          executionOrder: 0
```

```yaml
parallelBuild:
- name: test1
  buildTarget: BUILD
- name: test2
  buildTarget: BUILD
pipelines:
- nodes:
  - label: XXXXX
    executionOrder: 0
    stages:
    - name: XXXXX
      executionOrder: 0
  - label: test1
    executionOrder: 1
    stages:
    - name: BUILD
      executionOrder: 0
  - label: test2
    executionOrder: 1
    stages:
    - name: BUILD
      executionOrder: 0

```

**Comment by AdunSG** [comment]
Hi, i will Check when i'm Back from vacation.
You can Go with the workaround until then .

**Comment by Ch3ri0ur** [comment]
No worries. Take your time and have a nice vacation.

**Comment by AdrianCert** [comment]
The issue is that all other items that are siblings with `xyaml.for` will be shadowed due the processing. You simply need to put it in a separate object.

Here is your example:
```yaml
parallelBuild:
- name: test1
  buildTarget: BUILD
- name: test2
  buildTarget: BUILD

pipelines:
- nodes:
  - label: XXXXX
    executionOrder: 0
    stages:
      - name: "XXXXX"
        executionOrder: 0

  - label: Should stay
    executionOrder: 0
    stages:
      - name: "Should stay stage"
        executionOrder: 0

  - xyml.for: build_config:parallelBuild
    xyml.content:
    - label: "{{build_config.name}}"
      executionOrder: 1
      stages:
        - name: "{{build_config.buildTarget}}"
          executionOrder: 0
```
That produce:
```yaml
parallelBuild:
- name: test1
  buildTarget: BUILD
- name: test2
  buildTarget: BUILD
pipelines:
- nodes:
  - label: XXXXX
    executionOrder: 0
    stages:
    - name: XXXXX
      executionOrder: 0
  - label: Should stay
    executionOrder: 0
    stages:
    - name: Should stay stage
      executionOrder: 0
  - label: test2
    executionOrder: 1
    stages:
    - name: BUILD
      executionOrder: 0
  - label: test1
    executionOrder: 1
    stages:
    - name: BUILD
      executionOrder: 0
```

**Comment by AdunSG** [comment]
ok the problem is tougher than i though...

It is hard to keep the order in statements like this:
```
array:
- name: second
  value: 2
- name: third
  value: 3

commands:
  - name: first
    value: 1
    xyml.for: element:array
    xyml.content:
    - name: "{{element.name}}"
      value: "{{element.value}}"
  - name: fourth
    value: 4
```

I'm working on it and will provide a solution later this week. I will also release a new version then.
