### ISSUE TITLE
for loops reverse order when member of array

### ISSUE THREAD

**Issue by stoating** [AdunSG/yaml-extender#4]
```
array:
  - value: 1
  - value: 2
  - value: 3
  - value: 4

commands:
  - value: x
  - xyml.for: element:array
    value: "{{element.value}}"
```

expected:
```
commands:
  - value: x
  - value: 1
  - value: 2
  - value: 3
  - value: 4
```

actual:
```
commands:
  - value: x
  - value: 4
  - value: 3
  - value: 2
  - value: 1
```
