### ISSUE TITLE
Nested {{ }} fail

### ISSUE THREAD

**Issue by Ch3ri0ur** [AdunSG/yaml-extender#6]
Consider This input file:

```yaml
default_value: XXXX
config_value: ZZZZ
cmd: python -m pla --variant {{config_value:{{default_value}}}}
```

This will result in:

```yaml
default_value: XXXX
config_value: ZZZZ
cmd: python -m pla --variant ZZZZ}}
```

Notice the }}.

The Regex does not ensure that the correct corresponding brackets are used. 
Maybe iterating over the values and only resolving the inner most brackets (ensure no other "{{" is in the capture group) first might solve this.
