### ISSUE TITLE
Cleaner syntax for incuding with passing parameters

### ISSUE THREAD

**Issue by ditschi** [AdunSG/yaml-extender#9]
The current syntax for including other files with parameters is: 

```yaml
 xyml.include:
  - file1.yaml<<ref_1=456>>
  - file2.yaml
```

when passing more than a few parameters this quickly gets hard to read (and maintain) 
- the line length grows
- sorting the parameters is difficult

Therfore a cleaner syntax  like the one below would be beneficial

```yaml
 xyml.include:
  - path: file1.yaml
    values:  # Probably a better name for this ;) 
      ref_1: 456
      ref_2: {{ another_ref:some-default }}
  - path: file2.yaml
```

For includes without parameters  the one-line syntax `xyml.include: file1.yaml` still should be possible. But for more complex setups a cleaner syntax would be beneficial.
